name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir -p package/bin
          mkdir -p package/share/ip_filter
          cp build/ip_filter package/bin/
          cp ip_filter.tsv package/share/ip_filter/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            package/bin/ip_filter
            package/share/ip_filter/ip_filter.tsv
